### ISSUE TITLE
Remove AddConst

### ISSUE THREAD

**Issue by vladimir-ch** [gonum/floats#49]
In #27 @btracey mentioned that `AddConst` should be removed. It is just a wrapper around a simple loop but it is used at a couple of places in gonum (some of them added recently), so it looks like it is doing some service. What is the current opinion on this?

**Comment by Kunde21** [comment]
It could be removed or added to internal/asm in vectorized form like [this](https://github.com/Kunde21/numgo/blob/master/arithmetic_amd64.s#L61) to add some speed.

**Comment by kortschak** [comment]
@Kunde21 would you put together a PR for that with benchmarks?

**Comment by Kunde21** [comment]
I've been using some of these functions for vectorization practice.  I've got these lying around in different scratch files:
CumSum, CumProd, Div, Mul, Sum, Scale, AddConst, Distance(L=1), Distance(L=+Inf)

Some can be pulled from numgo with minor adjustments to remove the ndarray broadcasting inherant to that library.  I'll dig them up and pull them all into a PR with benchmarks (~3x speedup is the usual).  Should I send a PR for both floats and asm with implementations and calls? 

I'm going to work on Equal, EqualApprox, Same, HasNaN, Max, Min, and Span in my free time.

**Comment by kortschak** [comment]
I think the path here is to first send a post to gonum-dev indicating the intention and then given people are happy with it (I can see no real reason not to be) then send a PR to internal/asm and then here using the asm code - no assembler in floats directly.

**Comment by btracey** [comment]
It's probably not so terrible to have, especially since it's used in other places. I'm closing this. I think future additions should be subject to the "does it treat the data as a whole"
