### ISSUE TITLE
Build difficulties, missing function

### ISSUE THREAD

**Issue by kshedden** [gonum/floats#51]
I have run `go get github.com/gonum/internal/asm` then `go get github.com/gonum/floats`.  The latter yields 7 errors that appear to be related to missing assembly functions, see below.  Is this an issue or am I doing something wrong?

bash-4.1$ go get github.com/gonum/floats
\# github.com/gonum/floats
../../go_projects/src/github.com/gonum/floats/floats.go:27: undefined: asm.DaxpyUnitaryTo
../../go_projects/src/github.com/gonum/floats/floats.go:39: undefined: asm.DaxpyUnitaryTo
../../go_projects/src/github.com/gonum/floats/floats.go:56: undefined: asm.DaxpyUnitaryTo
../../go_projects/src/github.com/gonum/floats/floats.go:68: undefined: asm.DaxpyUnitaryTo
../../go_projects/src/github.com/gonum/floats/floats.go:702: undefined: asm.DscalUnitary
../../go_projects/src/github.com/gonum/floats/floats.go:732: undefined: asm.DaxpyUnitaryTo
../../go_projects/src/github.com/gonum/floats/floats.go:744: undefined: asm.DaxpyUnitaryTo

**Comment by btracey** [comment]
Did you have previous installations? I.e. is the problem fixed if you run

go get -u -t github.com/gonum/floats

**Comment by kshedden** [comment]
Thanks, that seemed to work.  I had a very old version on this machine.  You can close the issue.
